### ISSUE TITLE
Problems with Torch graph bindings

### ISSUE THREAD

**Issue by silvasean** [llvm/mlir-npcomp#138] opened 2020-12-07 23:48 UTC
Running into an issue

```
silvasean@silvasean0:~/pg/mlir-npcomp/mlir-npcomp$ source .env; python frontends/pytorch/test/graph_export/test_script_add3.py
Traceback (most recent call last):
  File "frontends/pytorch/test/graph_export/test_script_add3.py", line 21, in <module>
    def add3(t0, t1, t2):
TypeError: import_function(): incompatible function arguments. The following argument types are supported:
    1. (self: _torch_mlir.ModuleBuilder, arg0: torch::jit::StrongFunctionPtr) -> torch::jit::StrongFunctionPtr

Invoked with: <_torch_mlir.ModuleBuilder object at 0x7f81c3e8d0b0>, <torch.jit.ScriptFunction object at 0x7f81a8cb36d0>
```

1. For some reason, on my system pybind11.h is in two places, and despite our efforts in the CMakeLists.txt file the non-torch one seems to get used for the torch bindings

```
/usr/local/google/home/silvasean/.local/lib/python3.8/site-packages/pybind11/include/pybind11/pybind11.h
/usr/local/google/home/silvasean/.local/lib/python3.8/site-packages/torch/include/pybind11/pybind11.h
```

2. Even after I fix that by manually commenting out the necessary CMakeLists.txt lines, I get the same issue. Unclear why.

**Comment by stellaraccident** [comment] 2020-12-14 00:37
Ok, I created an isolated repro of the issue and tracked down the root cause. Repro repository here: https://github.com/stellaraccident/ptbindrepro

For these cross module types to work, the computed ABI string for pybind11 using modules must match. The main variable keys that go into the ABI string are (see detail/internals.h):
  `PYBIND11_COMPILER_TYPE`: (_gcc vs _clang)
  `PYBIND11_STDLIB`: (_libcpp vs _libstdcpp)
  `PYBIND11_BUILD_ABI` (`__GXX_ABI_VERSION` on Linux): Typically `cxxabi1011` on official PyTorch binary releases and `cxxabi1013` on my machine.

These are all overridable based on defines for cases where you need to match something else and believe it to be safe.

I wrote [a little script](https://github.com/stellaraccident/ptbindrepro/blob/master/detect_mismatched_pybind.py) that figures this out. For example `detect_mismatched_pybind.py torch ptbindrepro` on my sample repro prints this (with the FIX_FLAG commented out):

```
Importing torch...
  Current pybind11_internals:
    __pybind11_internals_v4_gcc_libstdcpp_cxxabi1011__
Importing ptbindrepro...
OUR PYBIND11_INTERNALS_ID: __pybind11_internals_v4_gcc_libstdcpp_cxxabi1013__
  Current pybind11_internals:
    __pybind11_internals_v4_gcc_libstdcpp_cxxabi1011__
    __pybind11_internals_v4_gcc_libstdcpp_cxxabi1013__
ERROR: pybind11_internals version mismatched across modules
Some pybind11 internals versions mismatched
```

I need to do a bit more research on the cxxabi specifics, and then I suspect that this calls for a cmake flag like `-DNPCOMP_TORCH_OFFICIAL_BINARY=ON` or something in order to rig things so that project developers can build against binary installs. This won't be a problem for "official" npcomp releases (whenever that is), because we will mate the build environment to be correct.

**Comment by stellaraccident** [comment] 2020-12-14 00:52
Ok, so the compile flags to match how FaceBook builds its binaries are:

```
CXXFLAGS="-D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -DPYBIND11_COMPILER_TYPE=\"_gcc\""
```

We should definitely have either a configure option or auto-detection for that.

**Comment by stellaraccident** [comment] 2020-12-14 00:59
Looks like `-fabi-version` was never implemented for clang (https://reviews.llvm.org/D12598). Here are the actual flags that work for GCC vs clang:

```
GCC_CXXFLAGS="-fabi-version=11"
CLANG_CXXFLAGS="-U__GXX_ABI_VERSION -D__GXX_ABI_VERSION=1011 -DPYBIND11_COMPILER_TYPE=\"_gcc\""
```

**Comment by stellaraccident** [comment] 2020-12-14 01:09
Also note that the pybind upgrades to allow these things to be twiddled only landed on Oct-16 (to support PyTorch). Binaries distributions older than that will not work.

https://github.com/pybind/pybind11/pull/2602

**Comment by silvasean** [comment] 2020-12-14 23:27
I still seem to be hitting this. Is there some version of PyTorch pip / pybind11 that I need to update to?

**Comment by stellaraccident** [comment] 2020-12-14 23:34
Darn. I did just do a clean build in a fresh python environment.

```
python -m venv ~/.venv/ptbin
source ~/.venv/ptbin/bin/activate
which python  # Should be under ~/.venv/ptbin
echo "
absl-py==0.11.0
astunparse==1.6.3
cachetools==4.1.1
certifi==2020.12.5
chardet==3.0.4
flatbuffers==1.12
gast==0.3.3
google-auth==1.23.0
google-auth-oauthlib==0.4.2
google-pasta==0.2.0
grpcio==1.32.0
h5py==2.10.0
idna==2.10
Keras-Preprocessing==1.1.2
Markdown==3.3.3
numpy==1.19.4
oauthlib==3.1.0
opt-einsum==3.3.0
Pillow==8.0.1
protobuf==3.14.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pybind11==2.6.1
requests==2.25.0
requests-oauthlib==1.3.0
rsa==4.6
six==1.15.0
tb-nightly==2.5.0a20201208
tensorboard-plugin-wit==1.7.0
termcolor==1.1.0
tf-estimator-nightly==2.5.0.dev2020120801
tf-nightly==2.5.0.dev20201208
torch==1.8.0.dev20201214+cpu
torchaudio==0.8.0.dev20201211
torchvision==0.9.0.dev20201210+cpu
typing-extensions==3.7.4.3
urllib3==1.26.2
Werkzeug==1.0.1
wrapt==1.12.1
" | pip install -r /dev/stding
```

Also double check that you don't have a system package for pybind11 installed (should be fine but I didn't test it and the version on most Ubuntus is pybind ABI version 3, whereas PyTorch is at 4 and will definitely conflict if it gets it wrong).

**Comment by silvasean** [comment] 2020-12-14 23:49
Looks the issue is that I was in an october version of the nightly pytorch packages.

This fixed it:

```
pip3 install --upgrade --pre torch torchvision -f https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html
```

Yay, thanks!

(so I don't think that folks getting started would run into this; it's just an artifact of me having an out of date nightly on my machine)

**Closed** 2020-12-14 23:49 UTC

**Comment by stellaraccident** [comment] 2020-12-14 23:53
Yes - buried in my rambling above was the caveat that this was just fixed in pybind11 on Oct-16 and shortly thereafter in pytorch.
